---
namespace: scaleuptechnologies
name: octavia_quota
version: 1.0.0
readme: README.md
authors:
  - Freerk-Ole Zakfeld <fzakfeld@scaleuptech.com>
description: An ansible collection for managing OpenStack Octavia Quotas
license:
  - MIT
license_file: LICENSE
tags: []
dependencies: {}
repository: https://github.com/ScaleUp-Technologies/octavia_quota
documentation: https://github.com/ScaleUp-Technologies/octavia_quota
homepage: https://github.com/ScaleUp-Technologies/octavia_quota
issues: https://github.com/ScaleUp-Technologies/octavia_quota/issues
